<?php

namespace UUP\Authentication;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-12 at 03:21:22.
 */
class DateTimeAuthenticatorTest extends \PHPUnit_Framework_TestCase
{

        /**
         * @var DateTimeAuthenticator
         */
        protected $pdt;
        /**
         * @var DateTimeAuthenticator
         */
        protected $cdt;
        /**
         * @var DateTimeAuthenticator
         */
        protected $fdt;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp()
        {
                $this->pdt = new DateTimeAuthenticator(time() - 90, time() - 30);
                $this->cdt = new DateTimeAuthenticator(time() - 30, time() + 30);
                $this->fdt = new DateTimeAuthenticator(time() + 30, time() + 90);
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown()
        {
                
        }

        /**
         * @covers UUP\Authentication\DateTimeAuthenticator::__get
         */
        public function test__get()
        {
                $this->assertTrue(is_int($this->cdt->start));
                $this->assertTrue(is_int($this->cdt->end));
        }

        /**
         * @covers UUP\Authentication\DateTimeAuthenticator::authenticated
         */
        public function testAuthenticated()
        {
                $this->assertTrue($this->cdt->authenticated());
                $this->assertFalse($this->pdt->authenticated());
                $this->assertFalse($this->fdt->authenticated());
        }

        /**
         * @covers UUP\Authentication\DateTimeAuthenticator::getUser
         */
        public function testGetUser()
        {
                $this->assertTrue(is_string($this->cdt->getUser()));
        }

}
