<?php

namespace UUP\Authentication;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-12 at 03:21:22.
 */
class DateTimeRestrictorTest extends \PHPUnit_Framework_TestCase
{

        /**
         * @var DateTimeRestrictor
         */
        protected $pdt;
        /**
         * @var DateTimeRestrictor
         */
        protected $cdt;
        /**
         * @var DateTimeRestrictor
         */
        protected $fdt;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp()
        {
                $this->pdt = new DateTimeRestrictor(time() - 90, time() - 30);
                $this->cdt = new DateTimeRestrictor(time() - 30, time() + 30);
                $this->fdt = new DateTimeRestrictor(time() + 30, time() + 90);
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown()
        {
                
        }

        /**
         * @covers UUP\Authentication\DateTimeRestrictor::__get
         */
        public function test__get()
        {
                $this->assertTrue(is_int($this->cdt->start));
                $this->assertTrue(is_int($this->cdt->end));
        }

        /**
         * @covers UUP\Authentication\DateTimeRestrictor::accepted
         */
        public function testAccepted()
        {
                $this->assertTrue($this->cdt->accepted());
                $this->assertFalse($this->pdt->accepted());
                $this->assertFalse($this->fdt->accepted());
        }

        /**
         * @covers UUP\Authentication\DateTimeRestrictor::getUser
         */
        public function testGetUser()
        {
                $this->assertTrue(is_string($this->cdt->getUser()));
        }

}
