<?php

namespace UUP\Authentication;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-28 at 11:18:53.
 */
class HostnameAuthenticatorTest extends \PHPUnit_Framework_TestCase
{

        /**
         * @var HostnameAuthenticator
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp()
        {
                $this->object = new HostnameAuthenticator();
                $_SERVER['REMOTE_ADDR'] = '127.0.0.1';
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown()
        {
                
        }

        /**
         * @covers UUP\Authentication\HostnameAuthenticator::setHostname
         */
        public function testSetHostname()
        {
                $this->assertEquals($this->object->getUser(), HostnameAuthenticator::localhost);
        }

        /**
         * @covers UUP\Authentication\HostnameAuthenticator::authenticated
         */
        public function testAuthenticated()
        {
                $hostname = 'www.example.com';
                $this->assertEquals($this->object->authenticated(), true);
                $this->object->setHostname($hostname);
                $this->assertEquals($this->object->authenticated(), false);
        }

        /**
         * @covers UUP\Authentication\HostnameAuthenticator::getUser
         */
        public function testGetUser()
        {
                $hostname = 'www.example.com';
                $this->assertEquals($this->object->getUser(), HostnameAuthenticator::localhost);
                $this->object->setHostname($hostname);
                $this->assertEquals($this->object->getUser(), $hostname);
        }

        /**
         * @covers UUP\Authentication\HostnameAuthenticator::login
         */
        public function testLogin()
        {
                $this->assertNull($this->object->login());
        }

        /**
         * @covers UUP\Authentication\HostnameAuthenticator::logout
         */
        public function testLogout()
        {
                $this->assertNull($this->object->login());
        }

}

class HostnameAuthenticatorTest4 extends HostnameAuthenticatorTest
{
        
}
