<?php

namespace UUP\Authentication\Storage;

use UUP\Authentication\Storage\FileStorage;
use UUP\Authentication\Storage\StorageImplTest;

require_once 'StorageImplTest.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-26 at 12:08:43.
 */
class FileStorageTest extends StorageImplTest
{

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp()
        {
                $this->object = new FileStorage(tempnam(sys_get_temp_dir(), __FILE__));
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown()
        {
                
        }

}
